### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by imlucas** [bichiliad/atom-jsfmt#12]
1. Edit any file + save
2. error occurs

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jsfmt](https://github.com/bichiliad/atom-jsfmt) package, v0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:762

TypeError: Cannot read property 'length' of null
  at Function.module.exports.JsfmtRunner.errorToLineNumber (/Users/lucas/.atom/packages/atom-jsfmt/lib/jsfmtRunner.coffee:123:15)
  at Function.module.exports.JsfmtRunner.errorToMessage (/Users/lucas/.atom/packages/atom-jsfmt/lib/jsfmtRunner.coffee:95:13)
  at Function.module.exports.JsfmtRunner.format (/Users/lucas/.atom/packages/atom-jsfmt/lib/jsfmtRunner.coffee:85:28)
  at /Users/lucas/.atom/packages/atom-jsfmt/lib/jsfmtRunner.coffee:55:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:594:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:317:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "isotope-ui",
      "afterglow-like"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
afterglow-like, v0.2.1
atom-jsfmt, v0.8.1
build, v0.38.0
color-picker, v2.0.5
command-logger, v0.23.0
editor-stats, v0.17.0
file-icons, v1.5.7
isotope-ui, v2.4.0
language-jade, v0.4.0
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-jshint, v0.1.6
minimap, v4.10.0
motepair, v0.20.0
regex-railroad-diagram, v0.8.0
travis-ci-status, v0.15.1
wercker-status, v1.0.5

# Dev
No dev packages
```

**Comment by bichiliad** [comment]
Ah, I got it. `String#match` returns `null` on a non match, not an empty array. Will push a fix soon.

**Comment by bichiliad** [comment]
I think this is fixed, feel free to submit another issue if you see anything weird.

**Comment by imlucas** [comment]
thx!

**Comment by imlucas** [comment]
@bichiliad Getting this again in 0.8.2 :(

**Comment by bichiliad** [comment]
@imlucas can you open a new ticket and include the stack trace you're getting?
